name: HeadDatabaseFree
main: de.pierreschwang.headdatabase.HeadDatabasePlugin
version: ${project.version}
api-version: 1.14

permissions:
  headdatabase.*:
    children:
      headdatabase.admin.reload: true
      headdatabase.use: true
